### ISSUE TITLE
1/13/2023 Review Ticket

### ISSUE THREAD

**Issue by TayKimmy** [anawandh/frontend-proj#2]
- [ ] [Tay Kim's Review Ticket](https://github.com/TayKimmy/VSCodeProject/issues/12)
- [ ] [Aditya Nawandhar's Review Ticket](https://github.com/Firestorm0986/CSPrepository2/issues/10)
- [ ] [Dillon Lee's Review Ticket](https://github.com/dillonlee06/VSCode-Fastpages-Project/issues/9#issue-1535863226)
- [ ] [Rohan Agarwal's Review Ticket](https://github.com/RohanAgr/RohanRepository/issues/12)

- [ ] [Tay Kim's Fastpages](https://taykimmy.github.io/VSCodeProject/)
- [ ] [Aditya Nawandhar's Fastpages](https://firestorm0986.github.io/CSPrepository2/)
- [ ] [Rohan Agarwal's Fastpages](https://rohanagr.github.io/RohanRepository/)
- [ ] [Dillon Lee's Fastpages](https://dillonlee06.github.io/VSCode-Fastpages-Project/)

Frontend Hacks Screenshot:

<img width="1279" alt="frontend-proj-ss" src="https://user-images.githubusercontent.com/107821010/212617877-1c0f5f49-9d81-46b2-84e1-0c99ffab2948.png">
