### ISSUE TITLE
1/22/23 Week 19 Review Ticket

### ISSUE THREAD

**Issue by TayKimmy** [anawandh/frontend-proj#3]
- [ ] [Tay's Review Ticket](https://github.com/TayKimmy/VSCodeProject/issues/13)
- [ ] [Aditya's Review Ticket](https://github.com/Firestorm0986/CSPrepository2/issues/11)
- [ ] [Dillon's Review Ticket](https://github.com/dillonlee06/VSCode-Fastpages-Project/issues/10#issue-1552619550)
- [ ] [Rohan's Review Ticket](https://github.com/RohanAgr/RohanRepository/issues/13)
