### ISSUE TITLE
1/24/23 Week 20 Review Ticket

### ISSUE THREAD

**Issue by TayKimmy** [anawandh/frontend-proj#4]
- [x] [Presentation Link](https://www.canva.com/design/DAFYt12pUbk/1M_CBtZTRDjvxRjV7_3AHw/view?utm_content=DA[…]m_campaign=designshare&utm_medium=link2&utm_source=sharebutton](https://www.canva.com/design/DAFYt12pUbk/1M_CBtZTRDjvxRjV7_3AHw/view?utm_content=DAFYt12pUbk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton))
- [x] [Project Link](https://firestorm0986.github.io/frontend-proj/)
- [x] [Scrum board](https://github.com/users/Firestorm0986/projects/2)

Summary - 
The website helps people empower themselves with essential knowledge about the electric car industry and learn more about them so that they can make informed decisions when they buy an electric car. This website will also have easter eggs on each page to help the users to gain knowledge about different things about electric cars and the industry like a game or a random fact generator. They will also be able to sign up and take notes on specific cars or things that they like on a notes tab on the home page.
" If you're not first, you're last" 

Individual aspects:
Tay - Live Rankings/Likes
Aditya - Random Fact Generator
Dillon - Car Game
Rohan - Car Builder/Car Aspects

Team aspects:
Notes page 
sign-up/log-in page

- [x] [Tay's Review Ticket](https://github.com/TayKimmy/VSCodeProject/issues/14)
- [x] [Aditya's Review Ticket](https://github.com/Firestorm0986/CSPrepository2/issues/12)
- [x] [Dillon's Review Ticket](https://github.com/dillonlee06/VSCode-Fastpages-Project/issues/11#issue-1563792265)
- [x] [Rohan's Review Ticket](https://github.com/RohanAgr/RohanRepository/issues/14)

CSA Notes - 
- Rebecca made a google slides
- showed the purpose of the program and certain procedures which will help them achieve whatever goal they want
- including a database to store and update data (personal database)
- There are many tabs for clubs with their reviews
- The google slides have a flow control --> procedures which will allow the code to be executed
- there are multiple databases, with permissions as to who can and cannot access them. 
- Frontend includes tables
- Club search using keywords and database
- AWS for the backend, and GitHub pages for the frontend
- There are modeling relationships and showing the flow from the backend to frontend
- Has a timeline --> each person must have a certain set of tasks, which are completed by certain deadlines
- scrum boards for organization
