### ISSUE TITLE
2/4/23 Week 21 Review Ticket

### ISSUE THREAD

**Issue by TayKimmy** [anawandh/frontend-proj#5]
- [ ] [Tay's Review Ticket](https://github.com/TayKimmy/VSCodeProject/issues/15)
- [ ] [Aditya's Review Ticket](https://github.com/Firestorm0986/CSPrepository2/issues/13)
- [ ] [Dillon's Review Ticket](https://github.com/dillonlee06/VSCode-Fastpages-Project/issues/12#issue-1571915300)
- [ ] [Rohan's Review Ticket](https://github.com/RohanAgr/RohanRepository/issues/15)

We made a new flask repository named Directories-Tri2. Here is a screenshot of the home page, with customizations so that it talks about our repository and our project.
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/107821010/216809548-9cd1977e-af98-4886-98cc-e2afad122633.png">

Here is a screenshot of the sign-up database. It includes a user's name, id, car, and password. It is not connected to the website yet, but we are currently working on it.
![image](https://user-images.githubusercontent.com/108041389/216809525-86e61f1a-9515-4320-a273-ca96fb60a91c.png)
